# Generated by Django 6.0.4 on 2026-04-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='学号')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('age', models.PositiveIntegerField(verbose_name='年龄')),
                ('class_name', models.CharField(max_length=50, verbose_name='班级')),
            ],
        ),
    ]
